// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prodot.Patterns.Cqrs.EfCore.Tests.TestHelpers.Context;

#nullable disable

namespace Prodot.Patterns.Cqrs.EfCore.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20220826152355_AddStrongIds")]
    partial class AddStrongIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2");

            modelBuilder.Entity("Prodot.Patterns.Cqrs.EfCore.Tests.TestHelpers.Context.TestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Prodot.Patterns.Cqrs.EfCore.Tests.TestHelpers.Context.TestEntityStrongId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrongIdEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
